# Generated by Django 6.0.6 on 2026-06-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlunoLab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=150)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("id_dental", models.CharField(max_length=50, unique=True)),
                (
                    "origem",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("DENTAL", "Dental Office")],
                        default="DENTAL",
                        max_length=20,
                    ),
                ),
                ("ultima_sincronizacao", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "aluno (lab)",
                "verbose_name_plural": "alunos (lab)",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=120)),
                ("coordenador", models.CharField(max_length=150)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "equipe",
                "verbose_name_plural": "equipes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=200)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("id_dental", models.CharField(max_length=50, unique=True)),
                ("processo_aberto", models.BooleanField(default=False)),
                ("data_previsao_retorno", models.DateField(blank=True, null=True)),
                (
                    "origem",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("DENTAL", "Dental Office")],
                        default="DENTAL",
                        max_length=20,
                    ),
                ),
                ("ultima_sincronizacao", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "paciente",
                "verbose_name_plural": "pacientes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Laboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=150)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("cnpj", models.CharField(blank=True, max_length=18)),
                (
                    "equipes",
                    models.ManyToManyField(
                        blank=True, related_name="laboratorios", to="gestao_lab.equipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "laboratorio",
                "verbose_name_plural": "laboratorios",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PedidoMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("previsao_entrega", models.DateField()),
                ("descricao_servico", models.TextField()),
                (
                    "data_envio",
                    models.DateField(
                        blank=True,
                        help_text="Data em que o material foi enviado ao laboratorio.",
                        null=True,
                    ),
                ),
                ("entregue", models.BooleanField(default=False)),
                ("data_entrega", models.DateField(blank=True, null=True)),
                ("faturado_paciente", models.BooleanField(default=False)),
                ("faturado_lab", models.BooleanField(default=False)),
                ("numero_nota_fiscal", models.CharField(blank=True, max_length=30)),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_DIA", "Em dia"),
                            ("A_CONFIRMAR", "A confirmar"),
                            ("ATRASADO", "Atrasado"),
                            ("CONCLUIDO", "Concluido"),
                        ],
                        default="EM_DIA",
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="gestao_lab.alunolab",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="gestao_lab.equipe",
                    ),
                ),
                (
                    "laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="gestao_lab.laboratorio",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="gestao_lab.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido de material",
                "verbose_name_plural": "pedidos de material",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Moldagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "faturado",
                    models.BooleanField(
                        default=False,
                        help_text="Paciente ja realizou o pagamento pelo procedimento.",
                    ),
                ),
                (
                    "entregue",
                    models.BooleanField(
                        default=False,
                        help_text="Moldagem ja foi entregue ao laboratorio.",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moldagens",
                        to="gestao_lab.alunolab",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moldagens",
                        to="gestao_lab.paciente",
                    ),
                ),
                (
                    "pedido_material",
                    models.OneToOneField(
                        blank=True,
                        help_text="Pedido de material gerado a partir desta moldagem.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moldagem_origem",
                        to="gestao_lab.pedidomaterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "moldagem",
                "verbose_name_plural": "moldagens",
                "ordering": ["-criado_em"],
            },
        ),
    ]
