# Generated by Django 6.0.6 on 2026-06-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_lab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COMPLETA", "Completa (manual)"),
                            ("AGENDADA", "Agendada (automática)"),
                        ],
                        default="COMPLETA",
                        max_length=20,
                    ),
                ),
                ("sucesso", models.BooleanField(blank=True, null=True)),
                ("erro", models.TextField(blank=True)),
                ("pacientes_criados", models.PositiveIntegerField(default=0)),
                ("pacientes_atualizados", models.PositiveIntegerField(default=0)),
                ("alunos_criados", models.PositiveIntegerField(default=0)),
                ("alunos_atualizados", models.PositiveIntegerField(default=0)),
                ("disparado_por", models.CharField(blank=True, max_length=50)),
                ("duracao_segundos", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "registro de sincronização",
                "verbose_name_plural": "registros de sincronização",
                "ordering": ["-criado_em"],
            },
        ),
    ]
