# Generated by Django 6.0.6 on 2026-06-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_lab", "0002_registro_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="cpf",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="paciente",
            name="cpf_responsavel",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="paciente",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_cep",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_cidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_complemento",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_estado",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_logradouro",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="paciente",
            name="endereco_numero",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="paciente",
            name="nome_responsavel",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="paciente",
            name="rg",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
