# Generated by Django 6.0.6 on 2026-07-02 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_lab", "0004_paciente_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="convenio",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="paciente",
            name="dados_confirmados_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="dados_confirmados_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pacientes_confirmados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
