# Generated by Django 6.0.6 on 2026-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_lab', '0005_paciente_confirmacao_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomaterial',
            name='cobranca_whatsapp_enviada_em',
            field=models.DateTimeField(blank=True, help_text='Última vez que este pedido entrou numa cobrança automática por WhatsApp ao laboratório — evita cobrar de novo no mesmo dia.', null=True),
        ),
    ]
