# Generated by Django 6.0.6 on 2026-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_lab", "0007_alunolab_nome_normalizado_paciente_nome_normalizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidomaterial",
            name="data_faturamento",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="Data em que o faturamento foi concluido (paciente E laboratorio). Derivado no save() a partir das duas flags — nao editar a mao.",
                null=True,
            ),
        ),
    ]
