# Generated by Django 6.0.6 on 2026-07-21 15:15
"""Reformula o status do pedido para as 4 categorias reais do negocio.

Remove ``A_CONFIRMAR`` (passa a contar como ``EM_DIA``) e introduz
``ENTREGUE_NAO_FATURADO`` — categoria que ja existia na pratica (um pedido
entregue com faturamento incompleto), mas que o calculo anterior classificava
erradamente como ``EM_DIA`` por nao ter um valor proprio para representa-la.
A migracao de dados recalcula o status de todo ``PedidoMaterial`` existente com
a mesma logica de ``calcular_status()`` (models.py), para que nenhum registro
fique com o valor antigo (``A_CONFIRMAR``) ou com a classificacao incorreta.
"""

from __future__ import annotations

from datetime import date

from django.db import migrations, models

STATUS_EM_DIA = "EM_DIA"
STATUS_ATRASADO = "ATRASADO"
STATUS_ENTREGUE_NAO_FATURADO = "ENTREGUE_NAO_FATURADO"
STATUS_A_CONFIRMAR = "A_CONFIRMAR"
STATUS_CONCLUIDO = "CONCLUIDO"


def _status_novo(pedido) -> str:
    if pedido.entregue:
        if pedido.faturado_paciente and pedido.faturado_lab:
            return STATUS_CONCLUIDO
        return STATUS_ENTREGUE_NAO_FATURADO
    if date.today() > pedido.previsao_entrega:
        return STATUS_ATRASADO
    return STATUS_EM_DIA


def _status_antigo(pedido) -> str:
    if pedido.entregue and pedido.faturado_paciente and pedido.faturado_lab:
        return STATUS_CONCLUIDO
    if not pedido.entregue and date.today() > pedido.previsao_entrega:
        return STATUS_ATRASADO
    if pedido.data_envio and not pedido.entregue:
        return STATUS_A_CONFIRMAR
    return STATUS_EM_DIA


def recalcular_com_logica_nova(apps, schema_editor):
    PedidoMaterial = apps.get_model("gestao_lab", "PedidoMaterial")
    atualizados = []
    for pedido in PedidoMaterial.objects.all():
        novo = _status_novo(pedido)
        if pedido.status != novo:
            pedido.status = novo
            atualizados.append(pedido)
    if atualizados:
        PedidoMaterial.objects.bulk_update(atualizados, ["status"])


def recalcular_com_logica_antiga(apps, schema_editor):
    PedidoMaterial = apps.get_model("gestao_lab", "PedidoMaterial")
    atualizados = []
    for pedido in PedidoMaterial.objects.all():
        antigo = _status_antigo(pedido)
        if pedido.status != antigo:
            pedido.status = antigo
            atualizados.append(pedido)
    if atualizados:
        PedidoMaterial.objects.bulk_update(atualizados, ["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_lab", "0009_backfill_data_faturamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidomaterial",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_DIA", "Em dia"),
                    ("ATRASADO", "Atrasado"),
                    ("ENTREGUE_NAO_FATURADO", "Entregue — não faturado"),
                    ("CONCLUIDO", "Concluido"),
                ],
                default="EM_DIA",
                editable=False,
                max_length=25,
            ),
        ),
        migrations.RunPython(recalcular_com_logica_nova, recalcular_com_logica_antiga),
    ]
