# Generated by Django 6.0.6 on 2026-07-21 23:14
"""Prepara AlunoLab para sincronizar do Eduq em vez do Dental Office.

Cria TurmaLab (o Eduq só lista alunos por turma, nunca por nome — precisa de
uma tabela local de turmas para saber o que sincronizar, mesma necessidade já
resolvida pelo gestao_cme com seu próprio modelo Turma). Renomeia
``id_dental`` para ``matricula`` (mesmo papel, nova fonte de dados) e
adiciona o vínculo ``turma``. Os valores existentes de ``id_dental`` são
preservados pela renomeação — a esta altura só sobram registros
``origem=MANUAL`` (a migração anterior já removeu todo ``origem=DENTAL``).
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_lab", "0011_remover_alunos_dental"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurmaLab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_normalizado",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=200
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=150)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("DENTAL", "Dental Office"),
                            ("EDUQ", "Eduq"),
                        ],
                        default="EDUQ",
                        max_length=20,
                    ),
                ),
                ("ultima_sincronizacao", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "turma (lab)",
                "verbose_name_plural": "turmas (lab)",
                "ordering": ["nome"],
            },
        ),
        migrations.RenameField(
            model_name="alunolab",
            old_name="id_dental",
            new_name="matricula",
        ),
        migrations.AlterField(
            model_name="alunolab",
            name="origem",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("DENTAL", "Dental Office"),
                    ("EDUQ", "Eduq"),
                ],
                default="EDUQ",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="origem",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("DENTAL", "Dental Office"),
                    ("EDUQ", "Eduq"),
                ],
                default="DENTAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alunolab",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alunos",
                to="gestao_lab.turmalab",
            ),
        ),
    ]
