[build]
builder = "RAILPACK"
buildCommand = "python gestao_cme/manage.py collectstatic --noinput"

[deploy]
preDeployCommand = "python gestao_cme/manage.py migrate --noinput"
startCommand = "gunicorn abo_goias.wsgi:application --chdir gestao_cme --bind 0.0.0.0:$PORT --workers 4 --threads 2 --worker-class gthread --timeout 120 --access-logfile - --error-logfile -"
healthcheckPath = "/healthz/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
