# Generated by Django 6.0.6 on 2026-06-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_aluno_localizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="abrigo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alunos",
                to="core.abrigo",
            ),
        ),
    ]
