# Generated by Django 6.0.6 on 2026-07-14 18:52

from django.db import migrations, models

from gestao_cme.utils import normalizar_texto


def preencher_nome_normalizado(apps, schema_editor):
    """Calcula o nome normalizado dos registros ja existentes.

    Sem isto, tudo que foi cadastrado antes desta migration ficaria com o campo
    vazio e desapareceria das buscas por nome.
    """

    for modelo in ("Aluno", "Turma"):
        Modelo = apps.get_model("core", modelo)
        registros = []
        for obj in Modelo.objects.all().only("id", "nome", "nome_normalizado"):
            obj.nome_normalizado = normalizar_texto(obj.nome)
            registros.append(obj)
        Modelo.objects.bulk_update(registros, ["nome_normalizado"], batch_size=500)


def limpar_nome_normalizado(apps, schema_editor):
    """Reversao: o campo e derivado, entao nao ha o que restaurar."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remover_usuario_coordenador_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_normalizado',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='turma',
            name='nome_normalizado',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200),
        ),
        migrations.RunPython(preencher_nome_normalizado, limpar_nome_normalizado),
    ]
