# Generated by Django 6.0.6 on 2026-07-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_aluno_nome_normalizado_turma_nome_normalizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="entrada_origem",
            field=models.ForeignKey(
                blank=True,
                help_text="Preenchido apenas em movimentacoes de SAIDA: aponta para a ENTRADA cujo pacote foi retirado.",
                limit_choices_to={"tipo": "ENTRADA"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saidas",
                to="core.movimentacao",
            ),
        ),
    ]
