# Generated by Django 6.0.6 on 2026-07-20 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_backfill_entrada_origem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoriaMovimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pacote_codigo", models.CharField(max_length=40)),
                ("aluno_nome", models.CharField(blank=True, max_length=150)),
                (
                    "acao",
                    models.CharField(
                        choices=[("EDICAO", "Edição"), ("EXCLUSAO", "Exclusão")],
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "movimentacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias",
                        to="core.movimentacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_movimentacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "auditoria de movimentação",
                "verbose_name_plural": "auditorias de movimentação",
                "ordering": ["-criado_em", "-id"],
            },
        ),
    ]
