# Generated by Django 6.0.6 on 2026-06-26 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestao_lab", "0003_enriquecimento_paciente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoGerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("bichectomia", "Bichectomia"),
                            ("toxina_botulinica", "Toxina Botulínica"),
                            ("odontopediatria", "Odontopediatria"),
                            ("endodontia", "Endodontia"),
                        ],
                        max_length=30,
                    ),
                ),
                ("observacoes_clinicas", models.TextField(blank=True)),
                ("profissional_nome", models.CharField(blank=True, max_length=200)),
                ("profissional_cro", models.CharField(blank=True, max_length=30)),
                (
                    "gerado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_gerados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos",
                        to="gestao_lab.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato gerado",
                "verbose_name_plural": "contratos gerados",
                "ordering": ["-criado_em"],
            },
        ),
    ]
