# Generated by Django 6.0.6 on 2026-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_contratos", "0005_tipos_contrato_genericos"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratogerado",
            name="hash_sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 do PDF gerado; recalculado após a assinatura.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="contratogerado",
            name="status",
            field=models.CharField(
                choices=[
                    ("gerado", "Gerado"),
                    ("aguardando_assinatura", "Aguardando assinatura"),
                    ("assinado", "Assinado"),
                    ("cancelado", "Cancelado"),
                ],
                default="gerado",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="contratogerado",
            name="versao",
            field=models.PositiveIntegerField(
                default=1, help_text="Sequencial por paciente e tipo de contrato."
            ),
        ),
    ]
