# Generated by Django 6.0.6 on 2026-07-02 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_contratos", "0007_backfill_versao_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contratogerado",
            name="arquivo_pdf_assinado",
            field=models.FileField(
                blank=True,
                help_text="PDF definitivo com a assinatura do paciente mesclada.",
                upload_to="contratos/assinados/",
            ),
        ),
        migrations.CreateModel(
            name="SessaoAssinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aberta", "Aberta pelo paciente"),
                            ("assinada", "Assinada"),
                            ("expirada", "Expirada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("expira_em", models.DateTimeField()),
                ("aberta_em", models.DateTimeField(blank=True, null=True)),
                ("assinada_em", models.DateTimeField(blank=True, null=True)),
                ("ip_assinatura", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "assinatura_imagem",
                    models.FileField(blank=True, upload_to="assinaturas/"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes_assinatura",
                        to="gestao_contratos.contratogerado",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessoes_assinatura_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sessão de assinatura",
                "verbose_name_plural": "sessões de assinatura",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="EventoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("sessao_criada", "Sessão de assinatura criada"),
                            ("contrato_aberto", "Contrato aberto pelo paciente"),
                            ("assinatura_concluida", "Assinatura concluída"),
                            ("documento_assinado_salvo", "Documento assinado salvo"),
                            ("sessao_expirada", "Sessão expirada"),
                            ("sessao_cancelada", "Sessão cancelada"),
                            (
                                "envio_dental_iniciado",
                                "Envio ao Dental Office iniciado",
                            ),
                            (
                                "envio_dental_concluido",
                                "Envio ao Dental Office concluído",
                            ),
                            ("envio_dental_erro", "Erro no envio ao Dental Office"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="gestao_contratos.contratogerado",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos",
                        to="gestao_contratos.sessaoassinatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de contrato",
                "verbose_name_plural": "eventos de contrato",
                "ordering": ["criado_em", "pk"],
            },
        ),
    ]
