# Generated by Django 6.0.6 on 2026-07-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_contratos", "0008_assinatura_remota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventocontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("sessao_criada", "Sessão de assinatura criada"),
                    ("contrato_aberto", "Contrato aberto pelo paciente"),
                    ("assinatura_concluida", "Assinatura concluída"),
                    ("documento_assinado_salvo", "Documento assinado salvo"),
                    ("sessao_expirada", "Sessão expirada"),
                    ("sessao_cancelada", "Sessão cancelada"),
                    ("envio_dental_iniciado", "Envio ao Dental Office iniciado"),
                    ("envio_dental_concluido", "Envio ao Dental Office concluído"),
                    ("envio_dental_erro", "Erro no envio ao Dental Office"),
                    ("whatsapp_iniciado", "Envio por WhatsApp iniciado"),
                    ("whatsapp_concluido", "Envio por WhatsApp concluído"),
                    ("whatsapp_erro", "Erro no envio por WhatsApp"),
                ],
                max_length=30,
            ),
        ),
    ]
