# Generated by Django 6.0.6 on 2026-07-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_contratos", "0009_whatsapp_evento_tipos"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessaoassinatura",
            name="identidade_confirmada_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento em que o paciente confirmou a data de nascimento cadastrada — obrigatório antes de liberar o canvas de assinatura.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sessaoassinatura",
            name="tentativas_identidade",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="eventocontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("sessao_criada", "Sessão de assinatura criada"),
                    ("contrato_aberto", "Contrato aberto pelo paciente"),
                    ("assinatura_concluida", "Assinatura concluída"),
                    ("documento_assinado_salvo", "Documento assinado salvo"),
                    ("sessao_expirada", "Sessão expirada"),
                    ("sessao_cancelada", "Sessão cancelada"),
                    ("identidade_confirmada", "Identidade do paciente confirmada"),
                    (
                        "identidade_bloqueada",
                        "Verificação de identidade bloqueada por excesso de tentativas",
                    ),
                    ("envio_dental_iniciado", "Envio ao Dental Office iniciado"),
                    ("envio_dental_concluido", "Envio ao Dental Office concluído"),
                    ("envio_dental_erro", "Erro no envio ao Dental Office"),
                    ("whatsapp_iniciado", "Envio por WhatsApp iniciado"),
                    ("whatsapp_concluido", "Envio por WhatsApp concluído"),
                    ("whatsapp_erro", "Erro no envio por WhatsApp"),
                ],
                max_length=30,
            ),
        ),
    ]
