# Generated by Django 6.0.6 on 2026-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_contratos", "0010_verificacao_identidade_paciente"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessaoassinatura",
            name="identidade_confirmada_como",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paciente", "Paciente"),
                    ("responsavel_legal", "Responsável legal"),
                ],
                help_text="Quem confirmou a identidade nesta sessão — o próprio paciente (data de nascimento) ou o responsável legal (CPF), quando o paciente é menor de idade. Fixado no momento da confirmação, independente de mudanças posteriores no cadastro.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sessaoassinatura",
            name="identidade_confirmada_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento em que a identidade de quem assina foi confirmada — obrigatório antes de liberar o canvas de assinatura.",
                null=True,
            ),
        ),
    ]
