# Generated by Django 6.0.6 on 2026-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_contratos", "0011_identidade_confirmada_como"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratogerado",
            name="carimbo_tempo",
            field=models.FileField(
                blank=True,
                help_text="Token RFC 3161 (TSR) emitido por uma autoridade de carimbo do tempo sobre o hash do PDF assinado — evidência independente do relógio do servidor de que o documento já existia naquele momento.",
                upload_to="contratos/carimbos/",
            ),
        ),
        migrations.AddField(
            model_name="contratogerado",
            name="carimbo_tempo_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora atestada pela autoridade de carimbo do tempo.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contratogerado",
            name="carimbo_tempo_tsa",
            field=models.CharField(
                blank=True,
                help_text="URL da autoridade de carimbo do tempo que emitiu o token.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="contratogerado",
            name="status_carimbo_tempo",
            field=models.CharField(
                choices=[
                    ("nao_solicitado", "Não solicitado"),
                    ("concluido", "Concluído"),
                    ("erro", "Erro ao solicitar"),
                ],
                default="nao_solicitado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventocontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("sessao_criada", "Sessão de assinatura criada"),
                    ("contrato_aberto", "Contrato aberto pelo paciente"),
                    ("assinatura_concluida", "Assinatura concluída"),
                    ("documento_assinado_salvo", "Documento assinado salvo"),
                    ("sessao_expirada", "Sessão expirada"),
                    ("sessao_cancelada", "Sessão cancelada"),
                    ("identidade_confirmada", "Identidade do paciente confirmada"),
                    (
                        "identidade_bloqueada",
                        "Verificação de identidade bloqueada por excesso de tentativas",
                    ),
                    ("envio_dental_iniciado", "Envio ao Dental Office iniciado"),
                    ("envio_dental_concluido", "Envio ao Dental Office concluído"),
                    ("envio_dental_erro", "Erro no envio ao Dental Office"),
                    ("whatsapp_iniciado", "Envio por WhatsApp iniciado"),
                    ("whatsapp_concluido", "Envio por WhatsApp concluído"),
                    ("whatsapp_erro", "Erro no envio por WhatsApp"),
                    (
                        "carimbo_tempo_iniciado",
                        "Solicitação de carimbo de tempo iniciada",
                    ),
                    ("carimbo_tempo_concluido", "Carimbo de tempo obtido"),
                    ("carimbo_tempo_erro", "Erro ao obter carimbo de tempo"),
                ],
                max_length=30,
            ),
        ),
    ]
