# Generated by Django 6.0.6 on 2026-07-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_contratos", "0012_carimbo_tempo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessaoassinatura",
            name="identidade_presencial_confirmada_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento em que o colaborador (criado_por) atestou ter verificado presencialmente a identidade de quem vai assinar, antes de iniciar a sessão — relevante quando o dispositivo de assinatura é compartilhado (ex.: tablet da recepção).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventocontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("sessao_criada", "Sessão de assinatura criada"),
                    ("contrato_aberto", "Contrato aberto pelo paciente"),
                    ("assinatura_concluida", "Assinatura concluída"),
                    ("documento_assinado_salvo", "Documento assinado salvo"),
                    ("sessao_expirada", "Sessão expirada"),
                    ("sessao_cancelada", "Sessão cancelada"),
                    ("identidade_confirmada", "Identidade do paciente confirmada"),
                    (
                        "identidade_bloqueada",
                        "Verificação de identidade bloqueada por excesso de tentativas",
                    ),
                    (
                        "identidade_presencial_confirmada",
                        "Identidade confirmada presencialmente pelo colaborador",
                    ),
                    ("envio_dental_iniciado", "Envio ao Dental Office iniciado"),
                    ("envio_dental_concluido", "Envio ao Dental Office concluído"),
                    ("envio_dental_erro", "Erro no envio ao Dental Office"),
                    ("whatsapp_iniciado", "Envio por WhatsApp iniciado"),
                    ("whatsapp_concluido", "Envio por WhatsApp concluído"),
                    ("whatsapp_erro", "Erro no envio por WhatsApp"),
                    (
                        "carimbo_tempo_iniciado",
                        "Solicitação de carimbo de tempo iniciada",
                    ),
                    ("carimbo_tempo_concluido", "Carimbo de tempo obtido"),
                    ("carimbo_tempo_erro", "Erro ao obter carimbo de tempo"),
                ],
                max_length=40,
            ),
        ),
    ]
