# Generated by Django 6.0.6 on 2026-07-07 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_contratos", "0013_identidade_presencial_confirmada"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminalAssinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=100)),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "terminal de assinatura",
                "verbose_name_plural": "terminais de assinatura",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="sessaoassinatura",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                help_text="Terminal dedicado para o qual esta sessão foi enviada, se houver.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessoes",
                to="gestao_contratos.terminalassinatura",
            ),
        ),
    ]
