# Generated by Django 6.0.6 on 2026-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_contratos", "0014_terminal_assinatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminalassinatura",
            name="ativado_em",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Quando o terminal foi ativado pela última vez — usado para desativação automática após TERMINAL_ATIVO_TTL_HORAS.",
                null=True,
            ),
        ),
    ]
