# Generated by Django 6.0.6 on 2026-07-10 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(help_text='Nome de usuário que deseja usar para entrar no sistema.', max_length=150, verbose_name='usuário desejado')),
                ('cargo', models.CharField(blank=True, help_text='Função/cargo na instituição — ajuda o administrador a decidir.', max_length=120)),
                ('justificativa', models.TextField(blank=True, help_text='Motivo do pedido de acesso (opcional).')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao_revisao', models.TextField(blank=True, help_text='Observação do administrador ao aprovar/rejeitar.')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_criado', models.ForeignKey(blank=True, help_text='Usuário criado quando esta solicitação foi aprovada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação de cadastro',
                'verbose_name_plural': 'solicitações de cadastro',
                'ordering': ['-criado_em'],
            },
        ),
    ]
